application:
  name: "Piperkt Users Service"
  version: "1.0.0"
mongodb:
  package-names:
    - piperkt.services.users.infrastructure.persistence
  uri: mongodb://users-mongo:password@users-mongo-svc.piper-kt.svc.cluster.local:27017/admin?authSource=admin&authMechanism=SCRAM-SHA-256&directConnection=true
micronaut:
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "pleaseChangeThisSecretForANewOne"
        generator:
          refresh-token:
            secret: "pleaseChangeThisSecretForANewOne"
spring:
  kafka:
    bootstrap-servers: cluster-kafka-bootstrap.piper-kt.svc.cluster.local:9094