application:
  name: "Piperkt Servers Service"
  version: "1.0.0"
mongodb:
  package-names:
    - piperkt.services.servers.infrastructure.persistence
micronaut:
  openapi:
    filename: "openapi-servers"
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "pleaseChangeThisSecretForANewOne"
        generator:
          refresh-token:
            secret: "pleaseChangeThisSecretForANewOne"
