"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.serviceRouter = void 0;
const express_1 = require("express");
const user_status_router_1 = require("./routers/user-status-router");
const jwt_1 = require("../commons/utils/jwt");
const serviceRouter = (0, express_1.Router)();
exports.serviceRouter = serviceRouter;
serviceRouter.use(jwt_1.JWTAuthenticationMiddleware);
serviceRouter.use("/users", user_status_router_1.userStatusRouter);
