apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{.Values.namespace}}
  name: {{.Values.serviceName}}
  labels:
    app: {{.Values.serviceName}}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{.Values.serviceName}}
  template:
    metadata:
      labels:
        app: {{.Values.serviceName}}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      serviceAccountName: micronaut-service
      containers:
        - name: {{.Values.serviceName}}
          image: zuccherosintattico/piperkt-{{.Values.serviceName}}
          imagePullPolicy: Always
          ports:
          {{- range .Values.containersPorts }}
            - name: {{.name}}
              containerPort: {{.containerPort}} 
          {{- end }}
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2048Mi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{.Values.namespace}}
  name: {{.Values.serviceName}}
spec:
  selector:
    app:  {{.Values.serviceName}}
  type: LoadBalancer
  ports:
    {{- range .Values.servicePorts }}
    - name: {{.name}}
      port: {{.port}}
      targetPort: {{.targetPort}}
      protocol: {{.protocol}}
    {{- end }}
