application:
  name: "Piperkt Users Service"
  version: "1.0.0"
mongodb:
  package-names:
    - piperkt.services.multimedia.infrastructure.persistence
  uri: mongodb://root:example@localhost:27017/admin?authSource=admin&authMechanism=SCRAM-SHA-256&directConnection=true
kafka:
  bootstrap:
    servers: localhost:9094
micronaut:
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "pleaseChangeThisSecretForANewOne"
        generator:
          refresh-token:
            secret: "pleaseChangeThisSecretForANewOne"
socket.io:
  port: 8082
