mongodb:
  uri: mongodb://root:example@localhost:27017/admin?authSource=admin&authMechanism=SCRAM-SHA-256&directConnection=true
kafka:
  bootstrap:
    servers: localhost:9094
socket.io:
  port: 8082
