apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: cluster
spec:
  kafka:
    resources:
      requests:
        memory: 512Mi
        cpu: "1"
      limits:
        memory: 1024Mi
        cpu: "1"
    version: 3.7.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: secure
        port: 9094
        type: nodeport
        tls: false
        configuration:
          brokers:
            - broker: 0
              advertisedHost: localhost
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.7"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 20Gi
        deleteClaim: false
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
  entityOperator:
    userOperator:
      resources:
        requests:
          memory: 100Mi
          cpu: "0.1"
        limits:
          memory: 512Mi
          cpu: "1"
    topicOperator:
      resources:
        requests:
          memory: 100Mi
          cpu: "0.1"
        limits:
          memory: 512Mi
          cpu: "1"

