apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: piper-kt
  name: notifications-service
  labels:
    app: notifications-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-service
  template:
    metadata:
      labels:
        app: notifications-service
    spec:
      containers:
        - name: notifications-service
          image: zuccherosintattico/piperkt-notifications-service
          env:
            - name: MONGO_URI
              value: "mongodb://notifications-mongo:password@notifications-mongo-svc.piper-kt.svc.cluster.local:27017/admin?authSource=admin&authMechanism=SCRAM-SHA-256&directConnection=true"
            - name: BROKER_URI
              value: "cluster-kafka-brokers.piper-kt.svc.cluster.local:9092"
            - name: PORT
              value: "8080"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  namespace: piper-kt
  name: notifications-service
spec:
  selector:
    app: notifications-service
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
      name: notifications-service
