apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  defaultBackend:
    service:
      name: frontend-service
      port:
        number: 8080

  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          {{- range $i, $path := .Values.notificationsServicePaths }}
          - pathType: {{ $path.type }}
            path: {{ $path.url }}
            backend:
              service:
                name: notifications-service
                port:
                  number: 8080
          {{- end }}
          {{- range $i, $path := .Values.usersServicePaths }}
          - pathType: {{ $path.type }}
            path: {{ $path.url }}
            backend:
              service:
                name: users-service
                port:
                  number: 8080
          {{- end }}
          {{- range $i, $path := .Values.friendshipsServicePaths }}
          - pathType: {{ $path.type }}
            path: {{ $path.url }}
            backend:
              service:
                name: friendships-service
                port:
                  number: 8080
          {{- end }}
          {{- range $i, $path := .Values.multimediaServicePaths }}
          - pathType: {{ $path.type }}
            path: {{ $path.url }}
            backend:
              service:
                name: multimedia-service
                port:
                  number: 8080
          {{- end }}
          {{- range $i, $path := .Values.serversServicePaths }}
          - pathType: {{ $path.type }}
            path: {{ $path.url }}
            backend:
              service:
                name: servers-service
                port:
                  number: 8080
          {{- end }}
          - pathType: ImplementationSpecific
            path: "/socket.io"
            backend:
              service:
                name: multimedia-service
                port:
                  number: 8082
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    app.kubernetes.io/component: controller
  name: nginx
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: k8s.io/ingress-nginx
