apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: micronaut-k8s
  name: "friendship-service"
spec:
  selector:
    matchLabels:
      app: "friendship-service"
  template:
    metadata:
      labels:
        app: "friendship-service"
    spec:
      serviceAccountName: micronaut-service # <1>
      containers:
        - name: "friendship-service"
          image: friendship-service # <2>
          imagePullPolicy: Never # <3>
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  namespace: micronaut-k8s
  name: "friendship-service" # <4>
spec:
  selector:
    app: "friendship-service"
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 8080 # <5>

---


