name: Deploy test images to Docker Hub -- Patch for development

on:
  push:
    branches:
      - merge/**
  workflow_dispatch:

jobs:
  image-delivery:
    name: ${{ matrix.service }} image delivery to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - "friendships-service"
          - "frontend-service"
          - "multimedia-service"
          - "notifications-service"
          - "servers-service"
          - "users-service"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Produce Dockerfile for ${{ matrix.service }}
        uses: DanySK/build-check-deploy-gradle-action@3.5.7
        with:
          should-run-codecov: false
          build-command: "./gradlew :${{ matrix.service }}:buildLayers && ./gradlew :${{ matrix.service }}:dockerfile"
          check-command: ":"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push ${{ matrix.service }} image
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.service }}/build/docker/main # path of Dockerfile generated by micronaut
          push: true
          platforms: |
            linux/amd64
            linux/arm64
          tags: |
            zuccherosintattico/piperkt-${{ matrix.service }}:test
